import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Navbar from "../../components/Navbar";
import { AppSidebar } from "../../components/AppSidebar";
import { ThemeProvider } from "../../components/Providers/theme-provider";
import { AuthProvider } from "../../components/Providers/AuthProvider";
import { SidebarProvider } from "@/components/ui/sidebar";
import PageLoaderWrapper from "@/components/PageLoaderWrapper";
import ProtectedRouteWrapper from "../../components/ProtectedRouteWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="w-full">
      <div
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            <ProtectedRouteWrapper allowedRoles={["admin"]}>
              <SidebarProvider>
                <AppSidebar />
                <div className="w-full">
                  <Navbar />
                  <div className="px-4 w-full">{children}</div>
                </div>
              </SidebarProvider>
            </ProtectedRouteWrapper>
          </AuthProvider>
        </ThemeProvider>
      </div>
    </main>
  );
}
